/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'z3on' at '3/15/16 10:39 PM' with Gradle 2.7
 *
 * @author z3on, @date 3/15/16 10:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
